apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ns.yml
    - dep.yml
    - svc_tcp.yml
    - svc_udp.yml

namespace: plex

commonLabels:
    app: plex

configMapGenerator:
    - name: plex-env-vars
      literals:
        - TZ=
        - PLEX_UID=
        - PLEX_GID=
        - ADVERTISE_IP=
        - HOSTNAME=
        - ALLOWED_NETWORKS=
        - PLEX_CLAIM=
