apiVersion: v1
kind: Service
metadata:
    name: plex-tcp
    labels:
        app: plex
spec:
    selector:
        app: plex
    ports:
      - name: "plex-home-thetr"
        targetPort: 3005
        port: 3005
        protocol: TCP
      - name: "plex-roku-contr"
        targetPort: 8324
        port: 8324
        protocol: TCP
      - name: "http-web"
        targetPort: 32400
        port: 32400
        protocol: TCP
      - name: "dlna-server-tcp"
        targetPort: 32469
        port: 32469
        protocol: TCP
