resources:
  - resources/namespace.yml
  - resources/clusterIssuer.yml
  - resources/gateway.yml
  - resources/certificate.yml

helmCharts:
  - includeCRDs: true
    name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    valuesFile: values.yml
    version: v1.13.3 # https://artifacthub.io/packages/helm/cert-manager/cert-manager

