resources:
  - resources/namespace.yml
  - resources/diskpool.yml

helmCharts:
  - name: mayastor
    repo: https://openebs.github.io/mayastor-extensions/ 
    version: 2.0.1
    releaseName: mayastor
    namespace: mayastor-system
    valuesFile: values.yml

namespace: mayastor-system
