# Obtained from https://github.com/kubernetes/kube-state-metrics/blob/master/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - service-account.yaml
  - service.yaml

commonLabels:
    app: kube-state-metrics

