apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'tj@tjzimmerman.com'
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: istio
          # gatewayHTTPRoute:
          #   parentRefs:
          #     - kind: Gateway
          #       name: personal-website
          #       namespace: personal-website
