apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-flashpool
  volumeName: rutorrent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-fileserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-client
  volumeName: rutorrent-fileserver
