# https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml
# https://kiali.io/docs/configuration/kialis.kiali.io/

cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      service_annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.40.100
      service_type: LoadBalancer
      view_only_mode: true
    external_services:
      prometheus:
        url: "http://prometheus-kube-prometheus-prometheus.prometheus-system.svc.cluster.local:9090/"
