# https://github.com/kubernetes-sigs/kustomize/issues/4381
resources:
  - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/main/docs/deploy/proxmox-csi-plugin.yml
  - resources/storageclass.yml

patches:
  - patch: |
      $patch: delete
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: proxmox-data
  - patch: |
      $patch: delete
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: proxmox-data-xfs
