apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-tv-shows
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/TV Shows
