apiVersion: v1
kind: Service
metadata:
    name: sonarr
spec:
    type: LoadBalancer
    selector:
        app: sonarr
    loadBalancerIP: 192.168.20.245
    ports:
    - name: "http-web"
      protocol: TCP
      targetPort: 8989
      port: 8989
