apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base/

patchesStrategicMerge:
  - dep.yml
  - svc.yml

configMapGenerator:
  - name: prometheus.yml
    files:
      - files/prometheus.yml
