apiVersion: apps/v1
kind: Deployment
metadata:
    name: personal-website
spec:
    replicas: 1
    selector:
        matchLabels:
            app: personal-website
    template:
        metadata:
            labels:
                app: personal-website
        spec:
            containers:
                - name: weatherpy
                  image: zimmertr/weatherpy:latest
                  volumeMounts:
                      - name: personal-website-weatherrc
                        mountPath: /root/.weatherrc
                        subPath: .weatherrc
                  resources:
                      limits:
                          memory: "100Mi"
                          cpu: .1
                - name: statsbot
                  image: zimmertr/statsbot:latest
                  resources:
                      limits:
                          memory: "100Mi"
                          cpu: .1
                - name: httpd
                  image: zimmertr/personal-website:latest
                  ports:
                      - name: "http-apache"
                        containerPort: 80
                        protocol: TCP
                  volumeMounts:
                      - name: personal-website-files
                        mountPath: /var/www/html/Files/
                      - name: personal-website-analyticsjs
                        mountPath: /var/www/html/analytics.js
                        subPath: analytics.js
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                      periodSeconds: 10
                      failureThreshold: 1
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      failureThreshold: 5
                  resources:
                      limits:
                          memory: "100Mi"
                          cpu: .1
            volumes:
                - name: personal-website-files
                  persistentVolumeClaim:
                    claimName: personal-website-files
                - name: personal-website-analyticsjs
                  configMap:
                    name: personal-website-analytics.js
                - name: personal-website-weatherrc
                  configMap:
                    name: personal-website-weatherrc
