---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "ns_personal_website.yml.j2"
            - "pv_personal_website_files.yml.j2"          
            - "pvc_personal_website_files.yml.j2"
            - "cm_personal_website_analyticsjs.yml.j2"
            - "cm_personal_website_weatherrc.yml.j2"
            - "svc_personal_website.yml.j2"
            - "dep_personal_website.yml.j2"

      - name: Waiting for the deployment to be ready.
        wait_for:
            host: "{{ hostname }}"
            port: 80
            timeout: 300
            msg: "Application was not available after 5 minutes. Something has probably gone wrong."
