apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: personal-website-files
spec:
    accessModes:
        - ReadOnlyMany
    resources:
        requests:
            storage: 1Gi
    volumeName: personal-website-files
