apiVersion: v1
kind: Service
metadata:
    name: personal-website
    labels:
        app: personal-website
spec:
    type: LoadBalancer
    selector:
        app: personal-website
    loadBalancerIP: 192.168.20.210
    ports:
    - name: "http-apache"
      protocol: TCP
      targetPort: 80
      port: 80
