apiVersion: v1
kind: Service
metadata:
    name: openvpn-tcp
    annotations:
        metallb.universe.tf/allow-shared-ip: "true"
    labels:
        app: openvpn
spec:
    type: LoadBalancer
    selector:
        app: openvpn
    loadBalancerIP: 192.168.20.237
    ports:
    - name: "http-web"
      protocol: TCP
      targetPort: 943
      port: 943
    - name: "tcp-traffic"
      protocol: TCP
      targetPort: 9443
      port: 9443
