apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ns.yml
    - dep.yml
    - svc.yml
    - pv_config.yml
    - pvc_config.yml
    - pv_plex.yml
    - pvc_plex.yml

namespace: tautulli

commonLabels:
    app: tautulli

configMapGenerator:
    - name: env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'

