---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "ns_tautulli.yml.j2"
            - "pv_tautulli_config.yml.j2"
            - "pvc_tautulli_config.yml.j2"
            - "pv_tautulli_plex.yml.j2"
            - "pvc_tautulli_plex.yml.j2"
            - "dep_tautulli.yml.j2"
            - "svc_tautulli.yml.j2"

      - name: Waiting for the deployment to be ready.
        wait_for:
            host: "{{ hostname }}"
            port: 8181
            timeout: 300
            msg: "Application was not available after 5 minutes. Something has probably gone wrong."
