apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: tautulli-plex
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: tautulli-plex
