apiVersion: v1
kind: Service
metadata:
    name: tautulli
    labels:
        app: tautulli
spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
    selector:
        app: tautulli
    loadBalancerIP: 192.168.20.146
    ports:
    - name: "http-web"
      protocol: TCP
      targetPort: 8181
      port: 8181
