namespace: personal-website

resources:
  - resources/namespace.yml
  - resources/analysisTemplate.yml
  - resources/rollout.yml
  - resources/service.yml
  - resources/istio/certificate.yml
  - resources/istio/gateway.yml
  - resources/istio/virtualService.yml
  # - resources/cilium/gateway.yml
  # - resources/cilium/httpRoute.yml

configMapGenerator:
  - name: test-connection-sh
    namespace: personal-website
    files:
      - files/test-connection.sh

generatorOptions:
 disableNameSuffixHash: true

images:
  - name: ghcr.io/zimmertr/personal-website
    # newTag: main-61d7f34
    newTag: main-58f3cb3 # Canary Banner
