controller:
  extraArgs:
    - --leader-elect
  metrics:
    enabled: true
  replicas: 2

dashboard:
  enabled: true
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.40.111
    type: LoadBalancer
