apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argo-system
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/zimmertr/Application-Manifests
        revision: main
        directories:
          - path: "*"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/zimmertr/Application-Manifests
        targetRevision: main
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
