apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argo-system
spec:
  generators:
    - git:
        repoURL: https://github.com/zimmertr/Application-Manifests
        revision: test
        directories:
          - path: "*"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/zimmertr/Application-Manifests
        targetRevision: test
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
          - group: admissionregistration.k8s.io
            kind: ValidatingWebhookConfiguration
            name: istiod-default-validator
            jsonPointers:
              - /webhooks/0/failurePolicy
          - group: admissionregistration.k8s.io
            kind: MutatingWebhookConfiguration
            name: istio-sidecar-injector
            jqPathExpressions:
              - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
