apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tks
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "TKS Applications"
  sourceRepos:
    - https://github.com/TJs-Kubernetes-Service/Application_Manifests
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  orphanedResources:
    warn: true
