apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idrac-exporter
bases:
    - ../../base/

patchesStrategicMerge:
    - dep.yml

secretGenerator:
  - name: idrac-exporter-telegraf-conf
    files:
      - telegraf.conf
