apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  storageClassName: saturnpool
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 12Ti
  accessModes:
    - ReadWriteOnce
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1584071025176-8081-zfs.csi.openebs.io
    volumeHandle: downloads
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: deluge-fileserver
# spec:
#   storageClassName: saturnpool
#   persistentVolumeReclaimPolicy: Retain
#   capacity:
#     storage: 12Ti
#   accessModes:
#     - ReadWriteOnce
#   csi:
#     driver: zfs.csi.openebs.io
#     fsType: zfs
#     volumeAttributes:
#       storage.kubernetes.io/csiProvisionerIdentity: 1584071025176-8081-zfs.csi.openebs.io
#     volumeHandle: deluge-fileserver
apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-fileserver
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
spec:
  storageClassName: flashpool
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1584071025176-8081-zfs.csi.openebs.io
    volumeHandle: config
