apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-anime
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Anime
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-audiobooks
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Audiobooks
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-cartoons
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Cartoons
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Plex/config
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-movies
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Movies
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-music
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Music
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-tv-shows
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/TV_Shows
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-unsorted
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Downloads/Unsorted
        server: earth.sol.milkyway
    storageClassName: nfs
