apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-anime
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-anime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-audiobooks
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-cartoons
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: plex-cartoons
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-config
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: plex-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-movies
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-music
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-tv-shows
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-tv-shows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-unsorted
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-unsorted
