apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: proxmox-flashpool
  volumeName: homepage-data
