apiVersion: v1
kind: Service
metadata:
  name: homepage
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.40.101
  labels:
    app: homepage
spec:
  type: LoadBalancer
  selector:
    app: homepage
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 3000
      port: 3000
