apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      initContainers:
        - name: bootstrap-volume
          image: busybox
          command:
            - sh
            - -c
            - cp /config/settings.yaml /app/config/settings.yaml
            - cp /config/background.jpg /app/config/background.jpg
          volumeMounts:
            - name: homepage-data
              mountPath: /app/config
            - name: homepage-settings
              mountPath: /config
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage
          envFrom:
            - configMapRef:
                name: homepage-env-vars
          ports:
            - name: "http"
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: homepage-data
              mountPath: /app/config
      volumes:
        - name: homepage-data
          persistentVolumeClaim:
            claimName: homepage-data
        - name: homepage-settings
          configMap:
            name: homepage-settings
