apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      initContainers:
        - name: bootstrap-volume
          image: busybox
          command:
            - sh
            - -c
            - mkdir -p /app/config/
            - cp /config/services.yaml /app/config/services.yaml
            - cp /config/settings.yaml /app/config/settings.yaml
            - mkdir -p /app/public/images
            - wget https://raw.githubusercontent.com/zimmertr/Kubernetes-Manifests/main/misc/homepage/files/background.jpg -o /app/public/images/background.jpg
            - wget https://raw.githubusercontent.com/zimmertr/Kubernetes-Manifests/main/misc/homepage/files/favicon.png -o /app/public/images/favicon.png
            - mkdir -p /app/public/icons
            - wget https://raw.githubusercontent.com/zimmertr/Kubernetes-Manifests/main/misc/homepage/files/supermicro-ipmi.svg -o /app/public/icons/supermicro-ipmi.svg
            - wget https://raw.githubusercontent.com/zimmertr/Kubernetes-Manifests/main/misc/homepage/files/kiali.svg -o /app/public/icons/kiali.svg
          volumeMounts:
            - name: homepage-data
              mountPath: /app/config
            - name: homepage-settings
              mountPath: /config
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage
          envFrom:
            - configMapRef:
                name: homepage-env-vars
          ports:
            - name: "http"
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: homepage-data
              mountPath: /app/config
      volumes:
        - name: homepage-data
          persistentVolumeClaim:
            claimName: homepage-data
        - name: homepage-settings
          configMap:
            name: homepage-settings
