---
# tasks file for prepare_os

- name: Installing package dependencies.
  apt:
    name: open-iscsi
    state: latest

- name: Enabling the iscsid Systemd unit.
  systemd:
    state: started
    enabled: yes
    name: iscsid

- name: Setting the admin context for the kubectl.
  command: kubectl config use-context kubernetes-admin@kubernetes
