apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: datapool
allowVolumeExpansion: true
parameters:
  fstype: "zfs"
  poolname: "DataPool"
  recordsize: "4k"
provisioner: zfs.csi.openebs.io
