apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
bases:
  - ../../../base

resources:
  - pv.yml
  - pvc.yml

patchesStrategicMerge:
  - dep.yml
  - svc.yml

images:
  - name: vault
    newTag: 1.8.4

commonLabels:
    app: vault
