apiVersion: v1
kind: PersistentVolume
metadata:
    name: vault-config
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Vault/config/
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vault-data
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Vault/data/
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vault-policies
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Vault/policies/
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
