apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: vault-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: vault-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-policies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: vault-policies
