apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: vault
  ports:
  - name: "http-web"
    targetPort: 8200
    port: 8200
  loadBalancerIP:
    192.168.50.166
