apiVersion: apps/v1
kind: Deployment
metadata:
  name: idrac-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idrac-exporter
  template:
    metadata:
      labels:
        app: idrac-exporter
    spec:
      containers:
        - name: idrac-exporter
          image: telegraf
