apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgres-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nextcloud-postgres-data
