resources:
  - resources/namespace.yml
  - resources/persistentVolume.yml
  - resources/persistentVolumeClaim.yml

namespace: prometheus-system

helmCharts:
  - includeCRDs: true
    name: kube-prometheus-stack
    namespace: prometheus-system
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values.yml
    version: 55.8.1 # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    additionalValuesFiles:
      - values-nginx-exporter.yml
