alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: proxmox-flashpool
          volumeName: alertmanager-data
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.40.112
    type: LoadBalancer

grafana:
  adminPassword: prom-operator
  persistence:
    type: pvc
    enabled: true
    storageClassName: proxmox-flashpool
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    existingClaim: grafana-data
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.40.110
    type: LoadBalancer

kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: proxmox-flashpool
          volumeName: prometheus-data
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.40.111
    type: LoadBalancer
