grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'NGINX'
          orgId: 1
          folder: 'NGINX'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/standard
  dashboards:
    default:
      NGINX:
        gnetId: 11199
        datasource: Prometheus

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: nginx-exporter
        metrics_path: /metrics
        static_configs:
          - targets: ['styx.sol.milkyway:9113']
      - job_name: 'istiod'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - istio-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: istiod;http-monitoring
      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: '.*-envoy-prom'
