grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'NGINX'
          orgId: 1
          folder: 'NGINX'
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/standard
  dashboards:
    NGINX:
      NGINX:
        gnetId: 11199
        datasource: Prometheus

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: nginx-exporter
        metrics_path: /metrics
        static_configs:
          - targets: ['styx.sol.milkyway:9113']
