apiVersion: v1
kind: Service
metadata:
  name: confluence
spec:
  selector:
    app: confluence
  ports:
  - name: "http-web"
    protocol: TCP
    targetPort: 8090
    port: 8090
  - name: "tcp-synchrony"
    protocol: TCP
    targetPort: 8091
    port: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: "tcp-postgres"
    protocol: TCP
    targetPort: 5432
    port: 5432
