apiVersion: apps/v1
kind: Deployment
metadata:
    name: plex
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: plex
    template:
        metadata:
            labels:
                app: plex
        spec:
            containers:
                - name: plex
                  image: plexinc/pms-docker:latest
                  envFrom:
                  - configMapRef:
                      name: env-vars
                  ports:
                      - name: "dlna-server-udp"
                        containerPort: 1900
                        protocol: UDP
                      - name: "gdm-discovery-1"
                        containerPort: 32410
                        protocol: UDP
                      - name: "gdm-discovery-2"
                        containerPort: 32412
                        protocol: UDP
                      - name: "gdm-discovery-3"
                        containerPort: 32413
                        protocol: UDP
                      - name: "gdm-discovery-4"
                        containerPort: 32414
                        protocol: UDP
                      - name: "plex-home-thetr"
                        containerPort: 3005
                        protocol: TCP
                      - name: "plex-roku-contr"
                        containerPort: 8324
                        protocol: TCP
                      - name: "http-web"
                        containerPort: 32400
                        protocol: TCP
                      - name: "dlna-server-tcp"
                        containerPort: 32469
                        protocol: TCP
                  volumeMounts:
                      - name: plex-audiobooks
                        mountPath: /audiobooks
                      - name: plex-config
                        mountPath: /config
                      - name: plex-tv-shows
                        mountPath: /tv
                      - name: plex-movies
                        mountPath: /movies
                      - name: plex-music
                        mountPath: /music
                      - name: plex-anime
                        mountPath: /anime
                      - name: plex-unsorted
                        mountPath: /unsorted
                  resources:
                      requests:
                          memory: 2048Mi
                          cpu: 1
                      limits:
                          memory: 10240Mi
                          cpu: 6
            volumes:
                - name: plex-audiobooks
                  persistentVolumeClaim:
                    claimName: plex-audiobooks
                - name: plex-config
                  persistentVolumeClaim:
                    claimName: plex-config
                - name: plex-tv-shows
                  persistentVolumeClaim:
                    claimName: plex-tv-shows
                - name: plex-movies
                  persistentVolumeClaim:
                    claimName: plex-movies
                - name: plex-music
                  persistentVolumeClaim:
                    claimName: plex-music
                - name: plex-anime
                  persistentVolumeClaim:
                    claimName: plex-anime
                - name: plex-unsorted
                  persistentVolumeClaim:
                    claimName: plex-unsorted
