apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-audiobooks
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Audiobooks
