apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-unsorted
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-unsorted
