apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-movies
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: plex-movies
