apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-config
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: plex-config
