apiVersion: v1
kind: Service
metadata:
    name: plex-tcp
    annotations:
        metallb.universe.tf/allow-shared-ip: "true"
    labels:
        app: plex
spec:
    type: LoadBalancer
    selector:
        app: plex
    loadBalancerIP: 192.168.20.230
    ports:
      - name: "plex-home-thetr"
        targetPort: 3005
        port: 3005
        protocol: TCP
      - name: "plex-roku-contr"
        targetPort: 8324
        port: 8324
        protocol: TCP
      - name: "http-web"
        targetPort: 32400
        port: 32400
        protocol: TCP
      - name: "dlna-server-tcp"
        targetPort: 32469
        port: 32469
        protocol: TCP
