apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -cR 33:33 /tmp/config/ /tmp/data/Kubernetes/NextCloud/userdata/"]
          volumeMounts:
            - name: nextcloud-config
              mountPath: /tmp/config
            - name: nextcloud-data
              mountPath: /tmp/data
        - name: postgres-wait
          image: postgres
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U nextcloud; do sleep 1; done;']
      containers:
        - name: nextcloud
          image: nextcloud
          envFrom:
            - configMapRef:
                name: nextcloud-env-vars
            - secretRef:
                name: nextcloud-password
          ports:
            - name: "http-web"
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nextcloud-config
              mountPath: /var/www/html/
            - name: nextcloud-data
              mountPath: /data
      volumes:
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
