apiVersion: batch/v1
kind: Job
metadata:
  name: toodo-schema-builder
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: postgres-wait
          image: postgres
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U toodo; do sleep 1; done;']
      containers:
      - name: toodo-schema-builder
        image: harbor.tjzimmerman.dev/tks/toodo:demo
        command: ["/bin/app",  "migrate"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
      restartPolicy: Never
  backoffLimit: 4
