apiVersion: v1
kind: Service
metadata:
  name: cilium-gateway
  namespace: kube-system
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
