---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "ns_jira.yml.j2"
            - "sec_postgres_password.yml.j2"
            - "pv_postgres_data.yml.j2"
            - "pv_jira_data.yml.j2"
            - "pvc_postgres_data.yml.j2"
            - "pvc_jira_data.yml.j2"
            - "dep_jira.yml.j2"
            - "dep_postgres.yml.j2"
            - "svc_jira.yml.j2" 
            - "svc_postgres.yml.j2" 
            
      - name: Waiting for the deployment to be ready.
        wait_for:
            host: "{{ hostname }}"
            port: 8080
            timeout: 300
            msg: "Application not available after 5 minutes. Something has probably gone wrong."
