apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-exporter
  template:
    metadata:
      labels:
        app: haproxy-exporter
    spec:
      containers:
        - name: haproxy-exporter
          image: prom/haproxy-exporter
