apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../base/

images:
    - name: linuxserver/radarr
      newTag: latest

resources:
    - pv.yml
    - pvc.yml
    # - vs.yml
    # - gw.yml

patchesStrategicMerge:
    - dep.yml
    - ns.yml
    - svc.yml

namespace: radarr

commonLabels:
    app: radarr

configMapGenerator:
    - name: radarr-env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'
