apiVersion: apps/v1
kind: Deployment
metadata:
  name: toodo
spec:
  selector:
    matchLabels:
      app: toodo
  template:
    metadata:
      labels:
        app: toodo
    spec:
      containers:
        - name: toodo
          image: harbor.tjzimmerman.dev/tks/toodo
