apiVersion: v1
kind: PersistentVolume
metadata:
    name: calibre-database
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Calibre/
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: calibre-books
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Ebooks/
        server: earth.sol.milkyway
    storageClassName: nfs
