controller:
  extraArgs:
    - --leader-elect
  metrics:
    enabled: true
  replicas: 2

dashboard:
  enabled: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.40.11
    type: LoadBalancer
