apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: federated-monitoring

resources:
  - ../../base/

patchesStrategicMerge:
  - HAProxy_Exporter/dep.yml
  - Prometheus/dep.yml
  - Prometheus/svc.yml

configMapGenerator:
  - name: prometheus.yml
    files:
      - Prometheus/files/prometheus.yml
