---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deleting the manifests from Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
            state: absent            
        with_items:
            - "pvc_prometheus_data.yml.j2"
            - "pvc_postgres_data.yml.j2"
            - "pvc_influxdb_data.yml.j2"
            - "pvc_grafana_config.yml.j2"
            - "pvc_grafana_data.yml.j2"
            - "pv_prometheus_data.yml.j2"
            - "pv_postgres_data.yml.j2"
            - "pv_influxdb_data.yml.j2"
            - "pv_grafana_data.yml.j2"
            - "pv_grafana_config.yml.j2"
            - "dep_grafana.yml.j2"
            - "dep_prometheus.yml.j2"
            - "dep_alertmanager.yml.j2"
            - "dep_postgres.yml.j2"
            - "dep_influxdb.yml.j2"
            - "svc_grafana.yml.j2" 
            - "svc_prometheus.yml.j2" 
            - "svc_alertmanager.yml.j2"
            - "svc_postgres.yml.j2"
            - "svc_influxdb.yml.j2"
            - "sec_postgres_password.yml.j2"
            - "sec_influxdb_password.yml.j2"
            - "sec_grafana_password.yml.j2"
            - "sec_smtp_password.yml.j2"
            - "cm_prometheus_configuration.yml.j2"
            - "cr_prometheus.yml.j2"
            - "crb_prometheus.yml.j2"

      - name: Removing the Grafana certificate directory.
        file:
            state: absent
            path: ~/.kube/grafana-prometheus-scraper

      - name: Unsetting the Grafana user.
        shell: kubectl config unset users.grafana-prometheus-scraper

      - name: Unsetting the Grafana user context.
        shell: kubectl config unset contexts.grafana-prometheus-scraper

      - name: Removing the certificate for Grafana.
        shell: kubectl delete csr grafana-prometheus-scraper
