---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "ns_grafana.yml.j2"
            - "cm_prometheus_configuration.yml.j2"
            - "sec_postgres_password.yml.j2"
            - "sec_grafana_password.yml.j2"
            - "sec_smtp_password.yml.j2"
            - "pv_prometheus_data.yml.j2"
            - "pv_postgres_data.yml.j2"
            - "pv_grafana_data.yml.j2"
            - "pv_grafana_logs.yml.j2"
            - "pv_grafana_config.yml.j2"
            - "pvc_prometheus_data.yml.j2"
            - "pvc_postgres_data.yml.j2"
            - "pvc_grafana_config.yml.j2"
            - "pvc_grafana_data.yml.j2"
            - "pvc_grafana_logs.yml.j2"
            - "dep_postgres.yml.j2"
            - "dep_alertmanager.yml.j2"
            - "dep_prometheus.yml.j2"
            - "dep_grafana.yml.j2"
            - "svc_grafana.yml.j2"
            - "svc_alertmanager.yml.j2"
            - "svc_prometheus.yml.j2"
            - "svc_postgres.yml.j2" 

      - name: Waiting for Alertmanager to be ready.
        wait_for:
            host: "{{ alertmanager_hostname }}"
            port: 9093
            timeout: 300
            msg: "Alertmanager was not available after 5 minutes. Something has probably gone wrong."

      - name: Waiting for Prometheus to be ready.
        wait_for:
            host: "{{ prometheus_hostname }}"
            port: 9090
            timeout: 300
            msg: "Prometheus was not available after 5 minutes. Something has probably gone wrong."

      - name: Waiting for Grafana to be ready.
        wait_for:
            host: "{{ grafana_hostname }}"
            port: 3000
            timeout: 300
            msg: "Grafana was not available after 5 minutes. Something has probably gone wrong."
