apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: argo-system
spec:
  generators:
    - git:
        repoURL: https://github.com/zimmertr/Kubernetes-Manifests
        revision: main
        directories:
          - path: "core/*"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
    spec:
      project: core
      source:
        repoURL: https://github.com/zimmertr/Kubernetes-Manifests
        targetRevision: main
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
