apiVersion: v1
kind: Service
metadata:
    name: openvpn-tcp
    labels:
        app: openvpn
spec:
    selector:
        app: openvpn
    ports:
    - name: "http-web"
      protocol: TCP
      targetPort: 943
      port: 943
    - name: "tcp-traffic"
      protocol: TCP
      targetPort: 9443
      port: 9443
---
apiVersion: v1
kind: Service
metadata:
    name: openvpn-udp
    labels:
        app: openvpn
spec:
    selector:
        app: openvpn
    ports:
    - name: "udp-traffic"
      protocol: UDP
      targetPort: 1194
      port: 1194
