apiVersion: v1
kind: PersistentVolume
metadata:
    name: nextcloud-config
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/NextCloud/data/
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nextcloud-data
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
