apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nextcloud
  ports:
  - name: "http-web"
    targetPort: 80
    port: 80
  loadBalancerIP:
    192.168.50.162
