---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "ns_nextcloud.yml.j2"
            - "sec_postgres_password.yml.j2"
            - "pv_postgres.yml.j2"
            - "pvc_postgres.yml.j2"
            - "pv_nextcloud_config.yml.j2"
            - "pvc_nextcloud_config.yml.j2"
            - "pv_nextcloud_data.yml.j2"
            - "pvc_nextcloud_data.yml.j2"
            - "dep_postgres.yml.j2"
            - "dep_nextcloud.yml.j2"
            - "svc_postgres.yml.j2"
            - "svc_nextcloud.yml.j2"

      - name: Waiting for the deployment to be ready.
        wait_for:
            host: "{{ hostname }}"
            port: 443
            timeout: 300
            msg: "Application was not available after 5 minutes. Something has probably gone wrong."
