---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deleting the Deluge manifests from Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
            state: absent            
        with_items:
            - "pv_radarr_config.yml.j2"
            - "pv_radarr_movies.yml.j2"
            - "pv_radarr_fileserver.yml.j2"
            - "pvc_radarr_config.yml.j2"
            - "pvc_radarr_movies.yml.j2"
            - "pvc_radarr_fileserver.yml.j2"
            - "dep_radarr.yml.j2"
            - "svc_radarr.yml.j2" 
