apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-movies
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Movies
