apiVersion: v1
kind: Service
metadata:
    name: personal-website
spec:
    selector:
        app: personal-website
    ports:
    - name: "http-apache"
      protocol: TCP
      targetPort: 80
      port: 80
