apiVersion: v1
kind: Service
metadata:
  name: toodo
  annotations:
  labels:
    app: toodo
spec:
  selector:
    app: toodo
  ports:
  - name: "http-toodo"
    protocol: TCP
    targetPort: 3000
    port: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: postgres
    labels:
        app: postgres
spec:
    selector:
        app: postgres
    ports:
    - name: "tcp-postgres"
      protocol: TCP
      targetPort: 5432
      port: 5432
