apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/

resources:
  - pv.yml
  - pvc.yml

patchesStrategicMerge:
  - dep.yml
  - dep_postgres.yml
  - svc.yml
  - ns.yml

namespace: confluence

images:
  - name: atlassian/confluence-server
    newTag: 7.13.0
  - name: postgres
    newTag: "10"

configMapGenerator:
  - name: confluence-env-vars
    literals:
      - ATL_DB_TYPE="postgresql"
      - ATL_JDBC_URL="jdbc:postgresql://postgres:5432/confluence?ssl=false"
      - ATL_JDBC_USER="confluence"
      - JVM_MAXIMUM_MEMORY=6144m
      - JVM_MINIMUM_MEMORY=512m
      - POSTGRES_USER=confluence

secretGenerator:
  - name: confluence-postgres-password
    envs:
      - confluence_postgres_password
