---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deleting the manifests from Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
            state: absent            
        with_items:
            - "pv_grocy_config.yml.j2"
            - "pvc_grocy_config.yml.j2"
            - "dep_grocy.yml.j2"
            - "svc_grocy.yml.j2" 
