apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden

resources:
  - dep.yml
  - pv.yml
  - pvc.yml
  - svc.yml

images:
  - name: postgres
    newTag: "11"

configMapGenerator:
  - name: vaultwarden-postgres-env-vars
    literals:
      - POSTGRES_USER=vaultwarden

secretGenerator:
  - name: vaultwarden-postgres-password
    envs:
      - postgres_password

commonLabels:
    app: postgres
