# https://gethomepage.dev/latest/configs/settings

title: sol.milkyway
startUrl: http://hub.sol.milkyway/

# Cannot be volume mounted in by ConfigMap as that resource cannot exceed 1Mb in size
background: https://raw.githubusercontent.com/zimmertr/Kubernetes-Manifests/main/misc/homepage/files/background.jpg
cardBlur: xl
favicon: https://raw.githubusercontent.com/zimmertr/Kubernetes-Manifests/main/misc/homepage/files/favicon.png
color: stone
