apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: calibre-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: calibre-books
