apiVersion: v1
kind: Service
metadata:
  labels:
    app: calibre
  name: calibre
  annotations:
      metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: calibre
  loadBalancerIP:
    192.168.50.161
  ports:
  - name: "http-desktop"
    targetPort: 8080
    port: 8080
  - name: "http-web"
    targetPort: 8081
    port: 8081
