configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    users.anonymous.enabled: "false"

crds:
  install: true
  keep:  false

global:
  revisionHistoryLimit: 3

applicationSet:
  metrics:
    enabled: true
  replicas: 2

controller:
  metrics:
    enabled: true

dex:
  metrics:
    enabled: true

notifications:
  metrics:
    enabled: true
  notifiers:
    service.email.gmail: |
      username: thomaszimmerman93@gmail.com
      password: $smtp-password
      host: smtp.gmail.com
      port: 465
      from: europa@tjzimmerman.com

redis-ha:
  enabled: true
  haproxy:
    IPv6:
      enabled: false

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.40.120
    type: LoadBalancer
