apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - dep.yml
  - pv.yml
  - pvc.yml
  - svc.yml

images:
  - name: postgres
    newTag: "11"

configMapGenerator:
  - name: vault-postgres-env-vars
    literals:
      - POSTGRES_USER=vault
  - name: vault-sql-init
    files:
      - init.sh

secretGenerator:
  - name: vault-postgres-password
    envs:
      - postgres_password

commonLabels:
    app: postgres
