apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: personal-website
  namespace: istio-gateway
spec:
  secretName: personal-website
  commonName: tjzimmerman.com
  dnsNames:
    - tjzimmerman.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
