apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test-connection
spec:
  args:
    - name: endpoint
    - name: header
  metrics:
    - name: test-connection
      successCondition: result == 'true'
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: curl-container
                    image: curlimages/curl:latest
                    volumeMounts:
                      - name: test-connection-sh
                        mountPath: /
                    env:
                    - name: HEADER
                      value: "{{ args.header }}"
                    - name: ENDPOINT
                      value: "{{ args.endpoint }}"
                    command:
                      - "/bin/sh"
                      - "/test-connection.sh"
                volumes:
                  - name: test-connection-sh
                    configMap:
                      name: test-connection-sh
