apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test-connection
  namespace: personal-website
spec:
  args:
    - name: endpoint
  metrics:
    - name: test-connection
      successCondition: result == 'true'
      provider:
        web:
          url: "{{ args.endpoint }}"
