apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test-connection
spec:
  args:
    - name: endpoint
    - name: header
  metrics:
    - name: test-connection
      successCondition: result == 'true'
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: curl-container
                    image: curlimages/curl:latest
                    command:
                      - "/bin/sh"
                      - "-c"
                      - 'curl -s -o /dev/null -w "%{http_code}" -H "{{ args.header }}" {{ args.endpoint }} | grep -q 200'
                  restartPolicy: Never
