apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
  namespace: personal-website-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: personal-website-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: personal-website-files
          configMap:
            name: personal-website-files
