apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: personal-website
spec:
  hostnames:
    - tjzimmerman.com
  parentRefs:
    - name: personal-website
  rules:
    - backendRefs:
        - name: personal-website
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: personal-website-metrics
spec:
  hostnames:
    - nix.sol.milkyway
  parentRefs:
    - name: personal-website
  rules:
    - matches:
      - path:
          value: "/"
      backendRefs:
        - name: personal-website
          port: 80
    - matches:
      - path:
          value: "/stub_status"
        port: 8080
      backendRefs:
        - name: personal-website
          port: 8080
