apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nix
spec:
  parentRefs:
    - name: personal-website
  rules:
    # - filters:
    #     - type: RequestRedirect
    #       requestRedirect:
    #         scheme: https
    #         statusCode: 301
    - backendRefs:
        - name: personal-website
          port: 80
