apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: personal-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website
  strategy:
    canary:
      maxUnavailable: 1
      steps:
        - setWeight: 100
        - experiment:
            templates:
              - name: canary
                specRef: canary
            analyses:
              - name: test-connection
                templateName: test-connection
                args:
                  - name: endpoint
                    value: "http://nix.sol.milkyway/"
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: personal-website-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: personal-website-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: personal-website-conf
          configMap:
            name: personal-website-conf
        - name: personal-website-files
          configMap:
            name: personal-website-files
