apiVersion: v1
kind: Service
metadata:
  name: personal-website-stable
spec:
  selector:
    app: personal-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website-canary
spec:
  selector:
    app: personal-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
