apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

images:
  - name: bitnami/redis
    newTag: "6.2"

resources:
  - dep.yml
  - pv.yml
  - pvc.yml
  - svc.yml

secretGenerator:
  - name: nextcloud-redis-password
    envs:
      - redis_password

commonLabels:
    app: redis
