apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/DataPool/Kubernetes/NextCloud/redis
    server: earth.sol.milkyway
  storageClassName: nfs-datapool
