---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the Service Accounts to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "ns_grafana.yml.j2"
            - "sa_cadvisor.yml.j2"
            - "sa_kube_state_metrics.yml.j2"
            - "sa_prometheus.yml.j2"
            - "cr_cadvisor.yml.j2"
            - "cr_kube_state_metrics.yml.j2"
            - "cr_prometheus.yml.j2"
            - "crb_cadvisor.yml.j2"
            - "crb_kube_state_metrics.yml.j2"
            - "crb_prometheus.yml.j2"

      - name: Retrieving the Bearer Token for the kube-state-metrics user.
        shell: "kubectl describe -n {{ namespace }} secrets kube-state-metrics-token | grep token: | awk '{print $2}'"
        register: kube_state_metrics_token

      - name: Retrieving the Bearer Token for the cadvisor user.
        shell: "kubectl describe -n {{ namespace }} secrets cadvisor-token | grep token: | awk '{print $2}'"
        register: cadvisor_token

      - name: Deploying the remaining manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "cm_grafana_dashboard_configuration.yml.j2"
            - "cm_grafana_datasource_configuration.yml.j2"
            - "cm_grafana_dashboards_1.yml.j2"
            - "cm_grafana_dashboards_2.yml.j2"
            - "cm_prometheus_configuration.yml.j2"
            - "cm_telegraf_configuration.yml.j2"
            - "cm_influxdb_configuration.yml.j2"
            - "cm_unifi_poller_configuration.yml.j2"
            - "sec_grafana_tokens.yml.j2"
            - "sec_varken_api_keys.yml.j2"
            - "sec_postgres_password.yml.j2"
            - "sec_influxdb_password.yml.j2"
            - "sec_grafana_password.yml.j2"
            - "sec_smtp_password.yml.j2"
            - "sec_pihole_exporter.yml.j2"
            - "psp_cadvisor.yml.j2"
            - "pv_prometheus_data.yml.j2"
            - "pv_postgres_data.yml.j2"
            - "pv_influxdb_data.yml.j2"
            - "pvc_prometheus_data.yml.j2"
            - "pvc_postgres_data.yml.j2"
            - "pvc_influxdb_data.yml.j2"
            - "ds_cadvisor.yml.j2"
            - "ds_node_exporter.yml.j2"
            - "dep_kube_state_metrics.yml.j2"
            - "dep_postgres.yml.j2"
            - "dep_influxdb.yml.j2"
            - "dep_telegraf.yml.j2"
            - "dep_alertmanager.yml.j2"
            - "dep_prometheus.yml.j2"
            - "dep_varken_exporter.yml.j2"
            - "dep_grafana.yml.j2"
            - "dep_unifi_poller.yml.j2"
            - "dep_pihole_exporter.yml.j2"
            - "svc_kube_state_metrics.yml.j2"
            - "svc_grafana.yml.j2"
            - "svc_alertmanager.yml.j2"
            - "svc_prometheus.yml.j2"
            - "svc_postgres.yml.j2"
            - "svc_influxdb_tcp.yml.j2"
            - "svc_influxdb_udp.yml.j2"
            - "svc_telegraf.yml.j2"
            - "svc_pihole_exporter.yml.j2"

      - name: Waiting for Alertmanager to be ready.
        wait_for:
            host: "{{ alertmanager_hostname }}"
            port: 9093
            timeout: 300
            msg: "Alertmanager was not available after 5 minutes. Something has probably gone wrong."

      - name: Waiting for Prometheus to be ready.
        wait_for:
            host: "{{ prometheus_hostname }}"
            port: 9090
            timeout: 300
            msg: "Prometheus was not available after 5 minutes. Something has probably gone wrong."

      - name: Waiting for InfluxDB to be ready.
        wait_for:
            host: "{{ influxdb_hostname }}"
            port: 8086
            timeout: 300
            msg: "InfluxDB was not available after 5 minutes. Something has probably gone wrong."

      - name: Waiting for Grafana to be ready.
        wait_for:
            host: "{{ grafana_hostname }}"
            port: 3000
            timeout: 600
            msg: "Grafana was not available after 10 minutes. Something has probably gone wrong."
