apiVersion: apps/v1
kind: Deployment
metadata:
  name: toodo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: toodo
  template:
    metadata:
      labels:
        app: toodo
        tier: frontend
    spec:
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: postgres-wait
          image: postgres
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U toodo; do sleep 1; done;']
      containers:
        - name: toodo
          image: harbor.tjzimmerman.dev/tks/toodo:demo
          envFrom:
            - configMapRef:
                name: toodo-env-vars
          ports:
            - name: "http-toodo"
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          # readinessProbe:
          #   httpGet:
          #       path: /
          #       port: 3000
          #   periodSeconds: 10
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #       path: /
          #       port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 5
