apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/

resources:
  - job.yml
  - istio

patchesStrategicMerge:
  - dep_toodo.yml
  - ns.yml
  - ss_postgres.yml

namespace: toodo

configMapGenerator:
  - name: toodo-env-vars
    literals:
      - POSTGRES_USER=toodo
      - POSTGRES_DB=toodo
      - DATABASE_URL=postgres://toodo:toodo@postgres:5432/toodo_production?sslmode=disable

secretGenerator:
  - name: toodo-secrets
    envs:
      - secrets/postgres.txt
