apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole-exporter
bases:
    - ../../base/

images:
  - name: ekofr/pihole-exporter
    newTag: v0.0.11

patchesStrategicMerge:
    - dep.yml
    - svc.yml

secretGenerator:
  - name: pihole-exporter-secret-vars
    envs:
      - pihole_exporter_secret_vars

configMapGenerator:
    - name: pihole-exporter-env-vars
      literals:
        - PIHOLE_HOSTNAME="explorer.sol.milkyway"
        - INTERVAL="60s"
        - PORT="9617"
