namespace: homepage-system

resources:
  - resources/namespace.yml
  - resources/persistentVolume.yml
  - resources/persistentVolumeClaim.yml
  - resources/service.yml
  - resources/statefulset.yml

images:
  - name: linuxserver/homepage
    newTag: v0.8.4 # https://github.com/gethomepage/homepage/pkgs/container/homepage

configMapGenerator:
  - name: homepage-env-vars
    literals:
      - PUID="65534"
      - PGID="65534"
