resources:
  - resources/namespace.yml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 5.24.0
    releaseName: argocd
    namespace: argo-system
    valuesFile: values.yml

namespace: argo-system
