apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.40.134
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 8989
      port: 80
