apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: "prometheus"
    protocol: TCP
    targetPort: 9090
    port: 9090

