apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/DataPool/Kubernetes/Calibre_Web/
    server: earth.sol.milkyway
  storageClassName: nfs
