apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: pihole-exporter
  labels:
    app: pihole-exporter
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.160
  selector:
    app: pihole-exporter
  ports:
    - name: pihole-exporter
      port: 9617
      protocol: TCP
      targetPort: 9617
