apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../base/

resources:
    - sc.yml

patchesStrategicMerge:
    - dep.yml

nameSuffix: -datapool

namespace: nfs-provisioner

images:
  - name: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
    newTag: v4.0.2

configMapGenerator:
  - name: nfs-datapool-env-vars
    literals:
      - PROVISIONER_NAME="datapool"
      - NFS_SERVER="earth.sol.milkyway"
      - NFS_PATH="/mnt/DataPool/Kubernetes"