apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      initContainers:
        - name: postgres-wait
          image: postgres
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U confluence; do sleep 1; done;']
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -cR 2002:2002 /var/atlassian/"]
          volumeMounts:
            - name: confluence-data
              mountPath: /var/atlassian/application-data/confluence
      containers:
        - name: confluence
          securityContext:
            runAsUser: 2002
            runAsGroup: 2002
          image: atlassian/confluence-server
          envFrom:
            - configMapRef:
                name: confluence-env-vars
            - secretRef:
                name: confluence-postgres-password
          ports:
            - name: "http-web"
              containerPort: 8090
              protocol: TCP
            - name: "tcp-synchrony"
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: confluence-data
              mountPath: /var/atlassian/application-data/confluence
      volumes:
        - name: confluence-data
          persistentVolumeClaim:
            claimName: confluence-data
