apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/DataPool/Kubernetes/Confluence/data
    server: earth.sol.milkyway
  storageClassName: nfs-datapool
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-postgres-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/DataPool/Kubernetes/Confluence/postgres
    server: earth.sol.milkyway
  storageClassName: nfs-datapool
