apiVersion: v1
kind: Service
metadata:
  name: confluence
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: confluence
  loadBalancerIP: 192.168.50.158
  ports:
  - name: "http-web"
    protocol: TCP
    targetPort: 8090
    port: 8090
  - name: "tcp-synchrony"
    protocol: TCP
    targetPort: 8091
    port: 8091
