apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: calibre-web-config
