apiVersion: v1
kind: Service
metadata:
  labels:
    app: calibre-web
  name: calibre-web
  annotations:
      metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: calibre-web
  loadBalancerIP:
    192.168.50.161
  ports:
  - name: "http"
    targetPort: 8083
    port: 8083
