apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.40.113
spec:
  selector:
    app: nginx-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: LoadBalancer
