apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-system
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.46.7
      helm:
        valueFiles:
          - $root/argo-cd/values.yml
    - repoURL: https://github.com/zimmertr/Application-Manifests
      targetRevision: HEAD
      ref: root
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
