apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-system
spec:
  project: default
  source:
    repoURL: https://github.com/zimmertr/Application-Manifests
    targetRevision: HEAD
    path: metallb
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
