apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-system
spec:
  project: default
  source:
    repoURL: https://github.com/zimmertr/Application-Manifests
    targetRevision: HEAD
    path: argo-cd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
