apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: radarr-config
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: radarr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: radarr-movies
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: radarr-movies
