apiVersion: v1
kind: Service
metadata:
    name: radarr
    labels:
        app: radarr
spec:
    selector:
        app: radarr
    ports:
    - name: "http-web"
      protocol: TCP
      targetPort: 7878
      port: 7878
