---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deleting the Deluge manifests from Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
            state: absent            
        with_items:
            - "pv_deluge_config.yml.j2"
            - "pv_deluge_downloads.yml.j2"
            - "pv_deluge_fileserver.yml.j2"
            - "pvc_deluge_config.yml.j2"
            - "pvc_deluge_downloads.yml.j2"
            - "pvc_deluge_fileserver.yml.j2"
            - "dep_deluge.yml.j2"
            - "svc_deluge.yml.j2" 
