apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-downloads
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Downloads/
