apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: deluge-fileserver
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: deluge-fileserver
