apiVersion: v1
kind: Service
metadata:
    name: deluge
    annotations:
    labels:
        app: deluge
spec:
    type: LoadBalancer
    selector:
        app: deluge
    loadBalancerIP: 192.168.20.220
    ports:
    - name: "traffic-1"
      protocol: TCP
      targetPort: 7850
      port: 7850
    - name: "traffic-2"
      protocol: TCP
      targetPort: 7851
      port: 7851
    - name: "http-deluge-web"
      protocol: TCP
      targetPort: 8112
      port: 8112
    - name: "daemon"
      protocol: TCP
      targetPort: 58846
      port: 58846

