apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ns.yml
    - dep.yml
    - dep_postgres.yml
    - svc.yml
    - svc_postgres.yml
    - pv_data.yml
    - pvc_data.yml
    - pv_postgres_data.yml
    - pvc_postgres_data.yml

namespace: jira

commonLabels:
    app: jira

configMapGenerator:
    - name: env-vars
      literals:
        - ATL_DB_TYPE="postgres72"
        - ATL_DB_DRIVER="org.postgresql.Driver"
        - ATL_JDBC_URL="jdbc:postgresql://postgres:5432/jira"
        - ATL_JDBC_USER="jira"
        - JVM_MAXIMUM_MEMORY=8096m
        - JVM_MINIMUM_MEMORY=1024m

secretGenerator:
    - name: jira-postgres-password
      envs:
        - postgres_password
