apiVersion: v1
kind: Service
metadata:
    name: jira
spec:
    type: LoadBalancer
    selector:
        app: jira
    loadBalancerIP: 192.168.20.207
    ports:
    - name: "http-web"
      protocol: TCP
      targetPort: 8080
      port: 8080
