apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nexus
  ports:
  - name: "nexus-http"
    targetPort: 8081
    port: 8081
  loadBalancerIP:
    192.168.50.165
