global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          origin: 'federated'

  - job_name: 'haproxy-exporter'
    static_configs:
      - targets: ['haproxy-exporter:9101']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics:8080']

  - job_name: 'kube-state-metrics-telemetry'
    static_configs:
      - targets: ['kube-state-metrics:8081']

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tks-node-1.sol.milkyway:9100']
      - targets: ['tks-node-2.sol.milkyway:9100']
      - targets: ['tks-node-3.sol.milkyway:9100']

  - job_name: 'cadvisor'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['tks-node-1.sol.milkyway:8080']
      - targets: ['tks-node-2.sol.milkyway:8080']
      - targets: ['tks-node-3.sol.milkyway:8080']

  - job_name: 'rtorrent-exporter'
    metrics_path: '/'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['rtorrent-exporter.rtorrent-exporter.svc.cluster.local:9135']
