apiVersion: v1
kind: PersistentVolume
metadata:
    name: tautulli-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs-datapool
    nfs:
        path: /mnt/DataPool/Kubernetes/Tautulli/
        server: earth.sol.milkyway
