apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: openvpn-config
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    volumeName: openvpn-config
