apiVersion: v1
kind: Service
metadata:
    name: openvpn-udp
    annotations:
        metallb.universe.tf/allow-shared-ip: "true"
    labels:
        app: openvpn
spec:
    type: LoadBalancer
    selector:
        app: openvpn
    loadBalancerIP: 192.168.20.237
    ports:
    - name: "udp-traffic"
      protocol: UDP
      targetPort: 1194
      port: 1194
