apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.159
  selector:
    app: prometheus
  ports:
  - name: "prometheus"
    protocol: TCP
    targetPort: 9090
    port: 9090

