apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      containers:
        - name: rutorrent
          image: crazymax/rtorrent-rutorrent
          envFrom:
          ports:
            - name: "http-rutorrent-web"
              containerPort: 8080
              protocol: TCP
