apiVersion: v1
kind: PersistentVolume
metadata:
    name: rutorrent-data
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/ruTorrent
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: rutorrent-fileserver
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/
        server: earth.sol.milkyway
    storageClassName: nfs-datapool
