apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: rutorrent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-fileserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: rutorrent-fileserver
