resources:
  - resources/namespace.yml
  - resources/cilium_load_balancer_ip_pool.yml
  # https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/#prerequisites
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/experimental-install.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.15.0-pre.1 # https://artifacthub.io/packages/helm/cilium/cilium
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yml
    includeCRDs: true
