apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: proxmox-flashpool
  volumeName: heimdall-data
