apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../../base/

resources:
    - pv.yml
    - pvc.yml
    # - pv_new.yml
    # - pvc_new.yml

patchesStrategicMerge:
    - dep.yml
    - ns.yml

namespace: deluge

configMapGenerator:
    - name: deluge-env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'
