apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-config
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Deluge
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-downloads
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Downloads/
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-fileserver
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/
        server: earth.sol.milkyway
    storageClassName: nfs
