apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  storageClassName: saturnpool
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fileserver
# spec:
#   storageClassName: saturnpool
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: deluge-fileserver
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 15Ti
    volumeName: deluge-fileserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  storageClassName: flashpool
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
