apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      initContainers:
        - name: postgres-wait
          image: postgres
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U vaultwarden; do sleep 1; done;']
      containers:
        - name: vaultwarden
          image: vaultwarden/server
          envFrom:
            - configMapRef:
                name: vaultwarden-env-vars
            - secretRef:
                name: vaultwarden-secrets
          ports:
            - name: "http-web"
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data
