apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../base/

resources:
    - pv.yml
    - pvc.yml
    - vs.yml
    - gw.yml

patchesStrategicMerge:
    - ns.yml
    - dep.yml

namespace: personal-website

commonLabels:
    app: personal-website

configMapGenerator:
    - name: personal-website-weatherrc
      files:
        - .weatherrc

    - name: personal-website-analytics.js
      files:
        - analytics.js
