apiVersion: v1
kind: Service
metadata:
  name: deluge
  annotations:
  labels:
    app: deluge
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.151
  selector:
    app: deluge
  ports:
  - name: "http-deluge-web"
    protocol: TCP
    targetPort: 8112
    port: 8112
  - name: "tcp-deluge-d"
    protocol: TCP
    targetPort: 58846
    port: 58846

