# https://gethomepage.dev/latest/configs/settings

title: sol.milkyway
startUrl: http://hub.sol.milkyway/

background: /images/background.jpg
cardBlur: xl
favicon: /images/favicon.png
color: stone

layout:
  Media:
    style: row
    columns: 4

hideVersion: true
