# kustomization.yml
namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.10.3

configMapGenerator:
- name: config
  files:
    - ./config

generatorOptions:
 disableNameSuffixHash: true
