apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr
          envFrom:
          - configMapRef:
              name: sonarr-env-vars
          ports:
              - name: "http-web"
                containerPort: 8989
                protocol: TCP
          volumeMounts:
              - name: sonarr-config
                mountPath: /config
              - name: sonarr-tv-shows
                mountPath: /tv
              - name: sonarr-anime
                mountPath: /anime
              - name: sonarr-cartoons
                mountPath: /cartoons
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-tv-shows
          persistentVolumeClaim:
            claimName: sonarr-tv-shows
        - name: sonarr-anime
          persistentVolumeClaim:
            claimName: sonarr-anime
        - name: sonarr-cartoons
          persistentVolumeClaim:
            claimName: sonarr-cartoons
