apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs-datapool
    nfs:
        path: /mnt/DataPool/Kubernetes/Sonarr/
        server: earth.sol.milkyway
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-tv-shows
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    storageClassName: nfs-datapool
    nfs:
        path: /mnt/DataPool/TV_Shows
        server: earth.sol.milkyway
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-anime
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    storageClassName: nfs-datapool
    nfs:
        path: /mnt/DataPool/Anime
        server: earth.sol.milkyway
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-cartoons
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    storageClassName: nfs-datapool
    nfs:
        path: /mnt/DataPool/Cartoons
        server: earth.sol.milkyway
