apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "sonarr"
spec:
  hosts:
    - phobos.sol.milkyway
  gateways:
    - sonarr
  http:
    - match:
      - uri:
          prefix: "/"
      route:
        - destination:
            host: "sonarr"
            port:
              number: 8989
